services:
  nodejs-app:
    image: nodejs-app:dev
    ports:
      - 80:80 # Or your custom port
    build:
      context: .
      dockerfile: dev.dockerfile
    # HMR support
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    # HMR support
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - nodejs-app

volumes:
  node_modules:

networks:
  nodejs-app
