showNewVersionIcon: false
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: 'hh : mm : ss'
trayOrders:
  -
    - icon
  -
    - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
connMode: true
connProfile: true
connProxy: 0
latencyTimeout: .nan
fontFamily: LXGW Bright Code TC
proxyOrder: 0
proxyDelayType: 1
latencyUrl: http://www.apple.com/library/test/success.html
theme: 0
mixinText: |
  # Last Edit: 2025-04-30
  mixin:
    # Ë¶ÜÁõñ DNS ÈÖçÁΩÆ
    dns:
      enable: true
      ipv6: true

      # Â¢ûÂº∫Ê®°ÂºèÔºåÊé®Ëçê‰ΩøÁî® fake-ip
      enhanced-mode: fake-ip
      # fake-ip Ê®°Âºè‰ΩøÁî®ÁöÑÂú∞ÂùÄÊ±†
      fake-ip-range: 198.18.0.1/16
      # fake-ip ÊéíÈô§ÂàóË°®ÔºåÊîØÊåÅÈÄöÈÖçÁ¨¶
      # ËÆæÁΩÆ‰∫ÜÈÄöÈÖçÁ¨¶ÁöÑÂüüÂêçÂøÖÈ°ª‰ΩøÁî®ÂºïÂè∑ÂåÖË£π
      # ÈÄöÈÖçÁ¨¶Ôºö
      #   - `*.` ÂåπÈÖçÂçïÁ∫ßÂ≠êÂüüÂêçÔºö'*.qq.com' ÂåπÈÖç a.qq.comÔºå‰∏çÂåπÈÖç qq.com
      #   - `.` ÂåπÈÖçÂ§öÁ∫ßÂ≠êÂüüÂêçÔºö'.qq.com' ÂåπÈÖç a.qq.com Âíå a.b.qq.comÔºå‰∏çÂåπÈÖç qq.com
      #   - `+.` ÂåπÈÖçÂ§öÁ∫ßÂ≠êÂüüÂêçÂíåËá™Ë∫´Ôºö'+.qq.com' ÂåπÈÖç a.qq.com„ÄÅa.b.qq.com Âíå qq.com
      fake-ip-filter:
        # Local & Internal
        - '*.lan'
        - '*.local'
        - '*.docker.internal'
        - WORKGROUP
        # Connect Test
        - '*.msftncsi.com'
        - '*.msftconnecttest.com'
        # NTP
        - 'ntp.ntsc.ac.cn'
        - '*.ntp.org.cn'
        - 'ntp.*.edu.cn'
        - 'time.*.edu.cn'
        - '+.pool.ntp.org'
        - 'ntp.*.com'
        - 'ntp1.*.com'
        - 'ntp2.*.com'
        - 'ntp3.*.com'
        - 'ntp4.*.com'
        - 'ntp5.*.com'
        - 'ntp6.*.com'
        - 'ntp7.*.com'
        - 'time.*.com'
        - 'time1.*.com'
        - 'time2.*.com'
        - 'time3.*.com'
        - 'time4.*.com'
        - 'time5.*.com'
        - 'time6.*.com'
        - 'time7.*.com'
        # Social Media
        - localhost.ptlogin2.qq.com
        # Music
        - '*.y.qq.com'
        - '*.music.tc.qq.com'
        - aqqmusic.tc.qq.com
        - '*.stream.qqmusic.qq.com'
        - '*.music.163.com'
        - '*.126.net'
        - songsearch.kugou.com
        - trackercdn.kugou.com
        - '*.kuwo.cn'
        - musicapi.taihe.com
        - music.taihe.com
        # Game
        - 'xbox.*.*.microsoft.com'
        - '*.*.xboxlive.com'
        - '*.n.n.srv.nintendo.net'
        - '*.stun.playstation.net'
        # STUN Server
        - '+.stun.*.*'
        - '+.stun.*.*.*'
        - '+.stun.*.*.*.*'
        - '+.stun.*.*.*.*.*'
        - '+.stun01.*.*'
        - 'stunserver.*'
        - 'stunserver.*.*'

      # default-nameserver Áî®‰∫éËß£Êûê nameserver Âíå fallback ‰∏≠ÁöÑ DNS ÊúçÂä°Âô®
      # Âõ†Ê≠§ÂøÖÈ°ªÊåáÂÆö IPÔºåÊîØÊåÅ UDP„ÄÅTCP„ÄÅDoT„ÄÅDoH
      # Clash ÊÄªÊòØ‰ΩøÁî®Á¨¨‰∏Ä‰∏™ÁªìÊûúÔºåÈÄÇÂΩìËÆæÁΩÆÂá†‰∏™ÂìçÂ∫îÂø´ÁöÑ DNS ÊúçÂä°Âô®Âç≥ÂèØ
      # default-nameserver:
      #   - '223.5.5.5' # ÈòøÈáå IPv4
      #   - '119.29.29.29' # ËÖæËÆØ IPv4
      #   - '[2400:3200::1]:53' # ÈòøÈáå IPv6
      #   - '[2402:4e00::]:53' # ËÖæËÆØ IPv6
      # nameserver ÊîØÊåÅ UDP„ÄÅTCP„ÄÅDoT„ÄÅDoH
      nameserver:
        - '223.5.5.5' # ÈòøÈáå IPv4
        - '119.29.29.29' # ËÖæËÆØ IPv4
        - '[2400:3200::1]:53' # ÈòøÈáå IPv6
        - '[2402:4e00::]:53' # ËÖæËÆØ IPv6
      # fallback ÂèØ‰ª•ÊåáÂÆö IP ÊàñÂüüÂêçÔºåÂêåÊ†∑ÊîØÊåÅ UDP„ÄÅTCP„ÄÅDoT„ÄÅDoH
      # ÈÖçÁΩÆ fallback ÂêéÈªòËÆ§ÂêØÁî® fallback-filter, geoip-code ÈªòËÆ§‰∏∫ CN
      fallback:
        - https://223.5.5.5/dns-query # ÈòøÈáå DoH, ECS Support
        - https://1.1.1.1/dns-query # Cloudflare DoH
        - https://8.8.8.8/dns-query # Google DoH
        - tls://223.5.5.5:853 # ÈòøÈáå DoT, ECS Support
        - tls://1.1.1.1:853 # Cloudflare DoT
        - tls://8.8.8.8:853 # Google DoT
      # fallback-filter ‰ºöÂØπ IP ËøõË°åËøáÊª§ÔºåÊòØÂØπÊäó DNS Ê±°ÊüìÊîªÂáªÁöÑ‰∏ÄÁßçÊé™ÊñΩ
      # 1. ÂΩì geoip ÂºÄÂêØ‰∏î code ËÆæÁΩÆ‰∏∫ CN Êó∂
      # Â±û‰∫é‰∏≠ÂõΩÁöÑ IP Â∞Ü‰ΩøÁî® nameserver ‰∏≠ÁöÑ dns
      # ÂÖ∂ÂÆÉÂõΩÂÆ∂ÁöÑ IP Â∞Ü‰ΩøÁî® fallback ‰∏≠ÁöÑ dns
      # 2. ÂΩìËØ∑Ê±ÇÁöÑÂüüÂêçÂåπÈÖç domain ‰∏î dns ÂìçÂ∫îÁöÑ ip ÂåπÈÖç ip-cidr Êó∂
      # Âº∫Âà∂‰ΩøÁî® fallback ‰∏≠ÁöÑ dns
      fallback-filter:
        geoip: true
        geoip-code: CN
        ip-cidr:
          - 240.0.0.0/4
        domain:
          - '+.google.com'
          - '+.facebook.com'
          - '+.twitter.com'
          - '+.youtube.com'
          - '+.xn--ngstr-lra8j.com'
          - '+.google.cn'
          - '+.googleapis.cn'
          - '+.googleapis.com'
          - '+.gvt1.com'

    # Ë¶ÜÁõñ Tun ÈÖçÁΩÆ
    tun:
      # TUN ËÆæÂ§áÂèØ‰ª•Áî®Êù•Â§ÑÁêÜ TCP„ÄÅUDP„ÄÅICMP ÊµÅÈáèÔºåÂ∞ÜÊµÅÈáèËΩ¨ÂèëÂà∞ËôöÊãüÁΩëÂç°ÔºåÂÆûÁé∞‰ª£ÁêÜ
      # ÈúÄË¶ÅÂú® `General -> Service Mode` ÂÆâË£ÖÊúçÂä°
      enable: true
      # Êé®Ëçê‰ΩøÁî® systemÔºåÈúÄË¶ÅÂú® `General -> Clash Core` Ê∑ªÂä†Èò≤ÁÅ´Â¢ôËßÑÂàô
      stack: system
      # ÂΩì fake-ip-range ÊòØ 198.18.0.1/16, Â∫îËØ•Âä´ÊåÅ 198.18.0.2:53ÔºåËØ∑Âãø‰øÆÊîπ
      dns-hijack:
        - 198.18.0.2:53
      # Ëá™Âä®ÁÆ°ÁêÜÁ≥ªÁªüË∑ØÁî±Ë°®ÔºåÂÆûÁé∞‰ª£ÁêÜÔºå‰ªÖÊé•Êî∂ IPv4 ÊµÅÈáè
      auto-route: true
      # Êõ¥Êé®Ëçê‰ΩøÁî® interface-name ÊåáÂÆöÁΩëÂç°ÂêçÁß∞
      auto-detect-interface: true
    # interface-name: 'tun0'
profileParsersText: >
  # Last Edit: 2025/05/06

  parsers:
    # `- reg: ^.*$` can match all subscriptions
    # `- url: https://example.com/profile.yaml` can match specified subscriptions
    - reg: ^.*$
      # Use the following code to process the subscription
      code: |
        module.exports.parse = (raw, { yaml }) => {
          const rawObj = yaml.parse(raw)

          // ---- STEP 1: Process proxies ----
          if (!rawObj?.proxies) {
            console.log('There are no proxies in the config.')
            return raw
          }

          const TRASH_PROXY_KEYS = ['ÊµÅÈáè', 'Âà∞Êúü', 'ÂØºËà™', 'ÈáçÁΩÆ']

          const CHINA_PROXY_KEYS = ['È¶ôÊ∏Ø', 'Êæ≥Èó®', 'Âè∞Êπæ', 'HongKong', 'Macau', 'Taiwan']
          const SINGAPORE_PROXY_KEYS = ['Êñ∞Âä†Âù°', 'Singapore']
          const JAPAN_PROXY_KEYS = ['Êó•Êú¨', 'Japan']
          const AMERICA_PROXY_KEYS = ['ÁæéÂõΩ', 'America']
          const GERMANY_PROXY_KEYS = ['Âæ∑ÂõΩ', 'Germany']
          const FRANCE_PROXY_KEYS = ['Ê≥ïÂõΩ', 'France']
          const ENGLAND_PROXY_KEYS = ['Ëã±ÂõΩ', 'England']
          const KOREA_PROXY_KEYS = ['Èü©ÂõΩ', 'Korea']

          // Filter out trash proxies
          const proxyNames = rawObj?.proxies?.filter(item => !TRASH_PROXY_KEYS.some(key => item.name.includes(key))).map(item => item.name) || []

          // Filter out proxies by country
          const proxyNamesChina = proxyNames.filter(item => CHINA_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesSingapore = proxyNames.filter(item => SINGAPORE_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesJapan = proxyNames.filter(item => JAPAN_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesAmerica = proxyNames.filter(item => AMERICA_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesGermany = proxyNames.filter(item => GERMANY_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesFrance = proxyNames.filter(item => FRANCE_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesEngland = proxyNames.filter(item => ENGLAND_PROXY_KEYS.some(key => item.includes(key))) || []
          const proxyNamesKorea = proxyNames.filter(item => KOREA_PROXY_KEYS.some(key => item.includes(key))) || []

          // Filter out proxies that are not matched with any country
          const proxyNamesOther = proxyNames.filter(item =>
            !CHINA_PROXY_KEYS.some(key => item.includes(key))
            && !SINGAPORE_PROXY_KEYS.some(key => item.includes(key))
            && !JAPAN_PROXY_KEYS.some(key => item.includes(key))
            && !AMERICA_PROXY_KEYS.some(key => item.includes(key))
            && !GERMANY_PROXY_KEYS.some(key => item.includes(key))
            && !FRANCE_PROXY_KEYS.some(key => item.includes(key))
            && !ENGLAND_PROXY_KEYS.some(key => item.includes(key))
            && !KOREA_PROXY_KEYS.some(key => item.includes(key)),
          ) || []

          // ---- STEP 2: Process proxy groups ----
          const proxyGroups = [
            {
              name: 'üëæ PROXY',
              type: 'select',
              proxies: [
                'ü•∞ CUTEST',
                'ü§£ ENJOY YOUR SELF',
              ],
            },
            {
              name: 'ü•∞ CUTEST',
              type: 'url-test',
              url: 'http://www.apple.com/library/test/success.html',
              interval: 180,
              tolerance: 60,
              proxies: proxyNames,
            },
            {
              name: 'ü§£ ENJOY YOUR SELF',
              type: 'select',
              proxies: [
                'üêº PANDA',
                'ü¶Å MERLION',
                'üê¶ NIPPON',
                'ü¶Ö EAGLE',
                'üêª BEAR',
                'üêì CHICKEN',
                'ü¶ú ROBIN',
                'ü™µ STICK',
                '‚ùî UNKNOWN',
              ],
            },
            {
              name: 'üêº PANDA',
              type: 'select',
              proxies: proxyNamesChina,
            },
            {
              name: 'ü¶Å MERLION',
              type: 'select',
              proxies: proxyNamesSingapore,
            },
            {
              name: 'üê¶ NIPPON',
              type: 'select',
              proxies: proxyNamesJapan,
            },
            {
              name: 'ü¶Ö EAGLE',
              type: 'select',
              proxies: proxyNamesAmerica,
            },
            {
              name: 'üêª BEAR',
              type: 'select',
              proxies: proxyNamesGermany,
            },
            {
              name: 'üêì CHICKEN',
              type: 'select',
              proxies: proxyNamesFrance,
            },
            {
              name: 'ü¶ú ROBIN',
              type: 'select',
              proxies: proxyNamesEngland,
            },
            {
              name: 'ü™µ STICK',
              type: 'select',
              proxies: proxyNamesKorea,
            },
            {
              name: '‚ùî UNKNOWN',
              type: 'select',
              proxies: proxyNamesOther,
            },
            {
              name: 'üëª GHOST',
              type: 'select',
              proxies: ['REJECT', 'DIRECT'],
            },
            {
              name: 'ü¶ì LOST',
              type: 'select',
              proxies: ['üëæ PROXY', 'DIRECT'],
            },
          ]
          // Set proxy groups
          rawObj['proxy-groups'] = proxyGroups

          // ---- STEP 3: Clean up DNS, rule providers and rules ----
          rawObj.dns = {}
          rawObj['rule-providers'] = []
          rawObj.rules = []

          return yaml.stringify({ ...rawObj })
        }

      # Use the following yaml config to insert rule providers
      yaml:
        # Insert rule providers
        # Recommend using https://gcore.jsdelivr.net/ CDN to accelerate GitHub resources in China
        mix-rule-providers:
          applications:
            type: http
            behavior: classical
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt'
            path: ./ruleset/applications.yaml
            interval: 86400
          private:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt'
            path: ./ruleset/private.yaml
            interval: 86400
          reject:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt'
            path: ./ruleset/reject.yaml
            interval: 86400
          icloud:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt'
            path: ./ruleset/icloud.yaml
            interval: 86400
          apple:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt'
            path: ./ruleset/apple.yaml
            interval: 86400
          google:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt'
            path: ./ruleset/google.yaml
            interval: 86400
          proxy:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt'
            path: ./ruleset/proxy.yaml
            interval: 86400
          direct:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt'
            path: ./ruleset/direct.yaml
            interval: 86400
          lancidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt'
            path: ./ruleset/lancidr.yaml
            interval: 86400
          cncidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt'
            path: ./ruleset/cncidr.yaml
            interval: 86400
          telegramcidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt'
            path: ./ruleset/telegramcidr.yaml
            interval: 86400

        # Insert rules
        # Rules are matched from top to bottom, that is, once a rule is hit, it will not be matched again
        prepend-rules:
          # Add your own rules here
          # Connect Test
          - DOMAIN,www.msftconnecttest.com,üëæ PROXY
          - DOMAIN,www.msftncsi.com,üëæ PROXY
          # Subscription service
          - DOMAIN,cm-sub.pz.pe,DIRECT
          # Game online
          - PROCESS-NAME,ForzaHorizon4.exe,DIRECT
          # Steam download service direct connection, save traffic
          - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
          - DOMAIN-SUFFIX,steamserver.net,DIRECT
          # Other
          - DOMAIN-SUFFIX,tampermonkey.net,üëæ PROXY

          # Recommended matching rules for providers
          - RULE-SET,applications,DIRECT # Process/application that needs to be directly connected
          - RULE-SET,private,DIRECT # Private domain that needs to be directly connected
          - RULE-SET,reject,üëª GHOST # Blocked domain
          - RULE-SET,icloud,DIRECT # iCloud
          - RULE-SET,apple,DIRECT # Apple
          - RULE-SET,google,üëæ PROXY # Google
          - RULE-SET,proxy,üëæ PROXY # Domain that needs to be proxied
          - RULE-SET,direct,DIRECT # Domain that needs to be directly connected
          - RULE-SET,lancidr,DIRECT # Local IP pool
          - RULE-SET,cncidr,DIRECT # Domestic IP pool
          - RULE-SET,telegramcidr,üëæ PROXY # Telegram IP pool
          - GEOIP,LAN,DIRECT
          - GEOIP,CN,DIRECT
          - MATCH,ü¶ì LOST
editor: 1
editorFontSize: 14
showNotifications: false
titleBarText: 'Current Mode: %mode%, Mixin Status: %mixin%. (,,¬¥‚Ä¢œâ‚Ä¢)„Éé"(¬¥„Å£œâ‚Ä¢ÔΩÄ„ÄÇ)'
trayProxiesStyle: 1
hideUnselectableGroup: false
showProxyFilter: true
connChainType: 2
checkForUpdates: false
childProcessText: |
  processes: # array
systemTheme: true
useModeIcons: true
